### ISSUE TITLE
Italian Delight's Pannetonne 

### ISSUE THREAD

**Issue by ImBummed** [Fiberoptic585/ParbelS1#5]
You cannot craft bread with Italian Delight's Panettone recipe.
The Panettone can be used to delete blocks permanently. 

To recreate the panettone breaking blocks, simply go to a wall and right click the wall. The block above will be replaced with the panettone.

This can be used to break bedrock.

THIS CAN BE USED TO BREAK ANYTHING

**Comment by Fiberoptic585** [comment]
fixed in latest release
