### ISSUE TITLE
Italian Delight should be removed

### ISSUE THREAD

**Issue by ImBummed** [Fiberoptic585/ParbelS1#7]
Italian delight seems to clash with Farmer's delight. The recipes change, and the food in Italian delight is bugged, especially the panettone. The food in ID also doesn't match the theme that this server is supposed to have -- that is to have an IMPROVED vanilla experience with as little change to the setting as possible. This means improvements to vanilla features, such as biomes o' plenty, matches, while adding in new themes, such as italian food, does not match. Brewing n' Chewing also has some conflicting thematic properties, but I think alcohol is kinda funny so it's aight.

**Comment by Fiberoptic585** [comment]
fixed in latest release
